# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - aksdemoazure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://aksdemocontainer09.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d1ace8d466784adfaaa3f43696a99136 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6c9005249fe748fa83358ab6d0b5399c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: aksdemocontainer09.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d1ace8d466784adfaaa3f43696a99136 }}/image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aksdemoazure'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b0a228fcd69b4abbb0153bfdf613dbe7 }}
        images: 'aksdemocontainer09.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d1ace8d466784adfaaa3f43696a99136 }}/image:${{ github.sha }}'